=== andrsparrow/HTP/BookStore/bin/librarySchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.qwerty.by/librarySchema" xmlns:tns="http://www.qwerty.by/librarySchema"
	elementFormDefault="qualified">

	<xs:element name="books" type="tns:books_type" />

	<xs:complexType name="books_type">
		<xs:sequence>
			<xs:element name="book" type="tns:book_type" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="book_type">
		<xs:sequence>
			<xs:element name="ISBN" type="tns:ISBN_type" minOccurs="0" maxOccurs="unbounded"  />
			<xs:element name="title" type="xs:string" />
			<xs:element name="pages" type="xs:int" />
			<xs:element name="author" type="tns:author_type"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" />
	</xs:complexType>

	<xs:complexType name="author_type">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="date-of-birth" type="xs:date" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" />
	</xs:complexType>

	<xs:complexType name="ISBN_type">
		<xs:attribute name="number" type="xs:int" />
	</xs:complexType>

</xs:schema>

=== andrsparrow/HTP/BookStore/bin/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns="http://www.qwerty.by/librarySchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.qwerty.by/librarySchema librarySchema.xsd">

	<book id="1">
		<title>Book1</title>
		<pages>10</pages>
		<author>
			<name>Author1</name>
			<date-of-birth>1962-11-07</date-of-birth>
		</author>
	</book>
	<book id="2">
		<ISBN number="0001" />
		<title>Book2</title>
		<pages>66</pages>
		<author>
			<name>Author2</name>
			<date-of-birth>1972-11-07</date-of-birth>
		</author>
	</book>
	<book id="3">
		<title>Book3</title>
		<pages>666</pages>
		<author>
			<name>Author2</name>
			<date-of-birth>1962-02-07</date-of-birth>
		</author>
	</book>
</books>
